### ISSUE TITLE
Add a Windows executable version

### ISSUE THREAD

**Issue by Jamtoad** [erde-lang/erde#35]
Fennel and Moonscript both have executable version. It would be neat if we could get a version of Erde in this form so that It can more easily be ran on Windows without having to install WSL.

**Comment by bsuth** [comment]
Good point, I have a windows partition I can mess around with this weekend, but I may be a bit slow since I rarely use Windows and will need some time to get familiar with it :sweat_smile:

**Comment by Jamtoad** [comment]
> Good point, I have a windows partition I can mess around with this weekend, but I may be a bit slow since I rarely use Windows and will need some time to get familiar with it :sweat_smile: 

I've compiled (I don't know if that's the correct term) a couple of my own Lua files into executables. If you tell me which Lua files from this repo are needed or that you think may be needed for the executable I may be able to mash something together tomorrow haha. I can give it a shot either way, I am desperate to try out this language!

**Comment by bsuth** [comment]
Sure, that would be great! It should be all `*.lua` files in the `erde` directory, but just in case, here is the list:

- cli.lua
- compile.lua
- config.lua
- constants.lua
- init.lua
- lib.lua
- stdlib.lua
- tokenize.lua
- utils.lua

Although they might still need to be in a subfolder called `erde`, otherwise `require` will probably fail to resolve (just a guess though)? 

The main entry point for the CLI is `cli.lua`, so on Linux the executable is basically just an alias to `lua erde/cli.lua`

**Comment by Jamtoad** [comment]
I was able to turn it into an executable. I am having some issues since it requires LFS.

**Comment by bsuth** [comment]
Hey @Jamtoad sorry about the delay!

I spent the last couple days reading several related projects (Luastatic, Fennel, Moonscript) and put together a repository over at https://github.com/erde-lang/erde-windows to handle building the windows executables. Indeed, getting `lfs` to work was quite tricky but I think I got something working (at least, it seems to work on my machine :eyes:).

I built executables for each of the major Lua version and attached a zip file in the [release page](https://github.com/erde-lang/erde/releases/tag/1.0.0-1). However, if you dont trust my executables you can also use the aforementioned repository to build them yourself (in that case, you should also replace the static Lua libraries in the repo with your own. The ones in the repository are from the official [LuaBinaries SourceForge](https://sourceforge.net/projects/luabinaries/files/)). Note that there is not an executable for LuaJIT, since there was no readily available static library for windows. I wasnt sure how difficult it would be to build one myself but figured that the existing executables should be enough. If there is enough demand in the future I am open to revisit this though.

Can you test out the executables and let me know if they work?

**Comment by Jamtoad** [comment]
Howdy @bsuth! No worries on the delay. I really appreciate you taking the time out to setup executables. They work perfectly! I tested the 5.1 version and it compiled a couple of `.erde` files without any issues! Thank you so much, I am super excited to give this language a try in a project I have going on!
